# **CONTEXTO**

Numa instituição de capacitação, temos uma tabela com as notas de 10 alunos do curso de "Análise de Dados com Numpy". As notas estão associadas a 3 tarefas (assignment1, 2 e 3) que foram aplicadas pelo instrutor ao longo do curso. Observar que cada aluno possui um único identificador (id). A escala das notas é de 0 a 100 pontos.

## **OBSERVAÇÃO**

O contexto aqui exposto não está baseado na descrição original do exercício da fonte de dados.

## **FONTE DE DADOS**

[StrataScratch - Coding Questions](https://platform.stratascratch.com/coding/10310-class-performance?code_type=2)

## **ATRIBUTOS**

1.   **id**: identificador do aluno
2.   **student**: nome do estudante
3.   **assigment1**: nota para o trabalho # 1
4.   **assigment2**: nota para o trabalho # 2
5.   **assigment3**: nota para o trabalho # 3

In [2]:
# importa as dependencias
from pandas import read_csv

In [3]:
# carrega os dados
notasAlunos = read_csv('/content/drive/MyDrive/Numpy training/dataset_ID_10310.csv', sep=';')
notasAlunos

   id         student  assignment1  assignment2  assignment3
0   1    Karen Austin           90           98           80
1   2    Matthew Ward           85           90           70
2   3    John Miranda           87           75           90
3   4    Scott Taylor           60           55           70
4   5    Tom Saunders           80           88           90
5   6  Natalie Palmer           55           70           65
6   7   James Burgess           72           70           75
7   8    Tracie Lopez           89           85           70
8   9   Donna Jimenez           91           90           98
9  10   Rachael Smith           76           66           80

In [5]:
# converte o Dataframe Pandas a Array Numpy por conveniência
notasAlunos = notasAlunos.values
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

## **P1 - Quanto tirou o aluno de id = 5 no "assignment1" ?**

In [ ]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [ ]:
# seleciona o historico do aluno de id=5
notasAlunos[4]

array([5, 'Tom Saunders', 80, 88, 90], dtype=object)

In [ ]:
# seleciona a nota
notasAlunos[4][2]

80

## **P2 - Quais são os nomes do 3ero, 4to e 5to alunos?**

In [ ]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [ ]:
# seleciona o histórico do 3ero, 4to e quinto aluno
notasAlunos[2:5]

array([[3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90]], dtype=object)

In [ ]:
# seleciona apenas os nomes do 3ero, 4to e quinto aluno
for aluno in notasAlunos[2:5]:
    print(aluno[1])

John Miranda
Scott Taylor
Tom Saunders

## **P3 - Quais são os nomes dos 3 melhores alunos no "assignment1"**?

In [ ]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [ ]:
# seleciona os históricos dos alunos com apenas as colunas students e assigment1
melAlus = []
for aluno in notasAlunos:
    melAlus.append(list(aluno[1:3]))
melAlus

[['Karen Austin', 90],
 ['Matthew Ward', 85],
 ['John Miranda', 87],
 ['Scott Taylor', 60],
 ['Tom Saunders', 80],
 ['Natalie Palmer', 55],
 ['James Burgess', 72],
 ['Tracie Lopez', 89],
 ['Donna Jimenez', 91],
 ['Rachael Smith', 76]]

In [ ]:
# ordena os históricos segundo a nota
melAlus.sort(key=lambda x: x[1],  reverse=True)
melAlus

[['Donna Jimenez', 91],
 ['Karen Austin', 90],
 ['Tracie Lopez', 89],
 ['John Miranda', 87],
 ['Matthew Ward', 85],
 ['Tom Saunders', 80],
 ['Rachael Smith', 76],
 ['James Burgess', 72],
 ['Scott Taylor', 60],
 ['Natalie Palmer', 55]]

In [ ]:
# captura o histórico doss 3 melhores alunos
melAlus[:3]

[['Donna Jimenez', 91], ['Karen Austin', 90], ['Tracie Lopez', 89]]

In [ ]:
# seleciona o nome dos 3 melhores alunos
for item in melAlus[:3]:
    print(item[0])

Donna Jimenez
Karen Austin
Tracie Lopez

## **P3 - Quais são os nomes dos 3 piores alunos no "assignment3"**?

In [ ]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [ ]:
# captura o histórico de todos os alunos considerando apenas a coluna "student" e "assignment3"
pioAluns = []
temp = []
for aluno in notasAlunos:
    temp.append(aluno[1])
    temp.append(aluno[4])
    pioAluns.append(temp)
    temp = []
pioAluns

[['Karen Austin', 80],
 ['Matthew Ward', 70],
 ['John Miranda', 90],
 ['Scott Taylor', 70],
 ['Tom Saunders', 90],
 ['Natalie Palmer', 65],
 ['James Burgess', 75],
 ['Tracie Lopez', 70],
 ['Donna Jimenez', 98],
 ['Rachael Smith', 80]]

In [ ]:
# ordena os históricos segundo a nota
pioAluns.sort(key=lambda x: x[1],  reverse=False)
pioAluns

[['Natalie Palmer', 65],
 ['Matthew Ward', 70],
 ['Scott Taylor', 70],
 ['Tracie Lopez', 70],
 ['James Burgess', 75],
 ['Karen Austin', 80],
 ['Rachael Smith', 80],
 ['John Miranda', 90],
 ['Tom Saunders', 90],
 ['Donna Jimenez', 98]]

In [ ]:
# seleciona o nome dos 3 piores alunos
for item in pioAluns[:3]:
    print(item[0])

Natalie Palmer
Matthew Ward
Scott Taylor

## **P4 - Calcula a média das notas de todos os alunos nos "assignment1, 2 e 3"**

In [6]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [11]:
# seleciona as notas
notasAlunos[:, 2:]

array([[90, 98, 80],
       [85, 90, 70],
       [87, 75, 90],
       [60, 55, 70],
       [80, 88, 90],
       [55, 70, 65],
       [72, 70, 75],
       [89, 85, 70],
       [91, 90, 98],
       [76, 66, 80]], dtype=object)

In [12]:
# calcula a média
notasAlunos[:, 2:].mean()

78.66666666666667

## **P5 - Quais alunos tiraram uma nota > a 70 no "assignment2"**?

In [ ]:
# mostra os dados
notasAlunos

array([[1, 'Karen Austin', 90, 98, 80],
       [2, 'Matthew Ward', 85, 90, 70],
       [3, 'John Miranda', 87, 75, 90],
       [4, 'Scott Taylor', 60, 55, 70],
       [5, 'Tom Saunders', 80, 88, 90],
       [6, 'Natalie Palmer', 55, 70, 65],
       [7, 'James Burgess', 72, 70, 75],
       [8, 'Tracie Lopez', 89, 85, 70],
       [9, 'Donna Jimenez', 91, 90, 98],
       [10, 'Rachael Smith', 76, 66, 80]], dtype=object)

In [15]:
# seleciona todos os alunos e suas notas no "assignment2"
assig2 = notasAlunos[:, (1, 3)]
assig2

array([['Karen Austin', 98],
       ['Matthew Ward', 90],
       ['John Miranda', 75],
       ['Scott Taylor', 55],
       ['Tom Saunders', 88],
       ['Natalie Palmer', 70],
       ['James Burgess', 70],
       ['Tracie Lopez', 85],
       ['Donna Jimenez', 90],
       ['Rachael Smith', 66]], dtype=object)

In [16]:
# condição
assig2[:,1] > 70

array([ True,  True,  True, False,  True, False, False,  True,  True,
       False])

In [17]:
assig2[assig2[:,1] > 70]

array([['Karen Austin', 98],
       ['Matthew Ward', 90],
       ['John Miranda', 75],
       ['Tom Saunders', 88],
       ['Tracie Lopez', 85],
       ['Donna Jimenez', 90]], dtype=object)