## **AMOSTRAGEM SISTEMÁTICA**

In [ ]:
# Importa as dependencias
import numpy as np
import pandas as pd

In [ ]:
# Monta o drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# carrega os dados
enem_sp = pd.read_csv('/content/drive/MyDrive/UDEMY - Estatística para Análise de Dados/Moreno Marcos/microdados_enem_2019_sp_tratado.csv',
                      sep=',', encoding='iso-8859-1')
enem_sp.head()

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Santa Isabel,22,M,1,parda,1,Santa Izabel do Pará,PA,1,4,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,São Paulo,17,F,1,parda,1,Belém,PA,2,0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,São Bernardo do Campo,19,M,1,parda,1,São Bernardo do Campo,SP,2,0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,Embu-Guaçu,17,F,1,parda,1,Itacoatiara,AM,2,0,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,Guarulhos,23,F,1,branca,1,São Paulo,SP,1,5,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

In [ ]:
# filtra os dados
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']
# reseta os índices para ordenação numérica
enem_campinas.reset_index(inplace=True)
enem_campinas

,index,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,15,Campinas,17,F,1,branca,1,Juazeiro do Norte,CE,1,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
1,31,Campinas,19,F,1,parda,1,Juiz de Fora,MG,1,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
2,51,Campinas,17,F,1,branca,1,Lavras,MG,2,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
3,116,Campinas,17,F,1,branca,1,Campinas,SP,2,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
4,169,Campinas,17,M,1,branca,1,Campinas,SP,2,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13193,499729,Campinas,18,M,1,branca,1,Campinas,SP,1,...,490.9,Inglês,1.0,120.0,100.0,100.0,100.0,0.0,420.0,Sim
13194,499749,Campinas,17,M,1,branca,1,Campinas,SP,2,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
13195,499862,Campinas,17,F,1,branca,1,Campinas,SP,2,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim
13196,499869,Campinas,19,F,1,branca,1,Campinas,SP,1,...,416.9,Espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13197,499883,Campinas,20,F,1,branca,1,Campinas,SP,1,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

O cojunto de dados (população Campinas) são ordenamors numericamente pelos seus índices. A regra da sequência numérica seria: selecionar o 1ero elemento (aleatoriamente) do cojunto de dados com incrementos de 100 em 100.

In [ ]:
# fixa a seleção aleatória
np.random.seed(2)
# escolhe aleatoriamente o primeiro elemento da amostra no intervalo 0 - 9 (pq?)
inicio = np.random.choice(10, 1)
inicio

array([8])

In [ ]:
# cria o conjunto de índices para seleção posterior 
indices1 = np.arange(inicio, len(enem_campinas), 100)
indices1

array([    5,   105,   205,   305,   405,   505,   605,   705,   805,
         905,  1005,  1105,  1205,  1305,  1405,  1505,  1605,  1705,
        1805,  1905,  2005,  2105,  2205,  2305,  2405,  2505,  2605,
        2705,  2805,  2905,  3005,  3105,  3205,  3305,  3405,  3505,
        3605,  3705,  3805,  3905,  4005,  4105,  4205,  4305,  4405,
        4505,  4605,  4705,  4805,  4905,  5005,  5105,  5205,  5305,
        5405,  5505,  5605,  5705,  5805,  5905,  6005,  6105,  6205,
        6305,  6405,  6505,  6605,  6705,  6805,  6905,  7005,  7105,
        7205,  7305,  7405,  7505,  7605,  7705,  7805,  7905,  8005,
        8105,  8205,  8305,  8405,  8505,  8605,  8705,  8805,  8905,
        9005,  9105,  9205,  9305,  9405,  9505,  9605,  9705,  9805,
        9905, 10005, 10105, 10205, 10305, 10405, 10505, 10605, 10705,
       10805, 10905, 11005, 11105, 11205, 11305, 11405, 11505, 11605,
       11705, 11805, 11905, 12005, 12105, 12205, 12305, 12405, 12505,
       12605, 12705, 12805, 12905, 13005, 13105])

In [ ]:
# visualiza tamanho do conj. de índices
len(indices1)

132

Utilizamos o cojunto de índices anterior criado para selecionar sistematicamente a amostra da população Campinas.

In [ ]:
amos_sistematica = enem_campinas.iloc[indices1,:]
amos_sistematica

,index,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
5,186,Campinas,19,F,1,branca,1,Campinas,SP,1,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
105,4910,Campinas,18,F,1,preta,1,Campinas,SP,1,...,451.5,Inglês,1.0,120.0,140.0,140.0,140.0,60.0,600.0,Sim
205,9002,Campinas,27,F,1,parda,1,Campinas,SP,1,...,373.4,Espanhol,1.0,120.0,120.0,120.0,120.0,20.0,500.0,Sim
305,13528,Campinas,18,F,1,branca,1,Campinas,SP,2,...,562.7,Inglês,1.0,140.0,120.0,120.0,140.0,120.0,640.0,Sim
405,18130,Campinas,30,F,1,parda,1,Campinas,SP,1,...,73.2,Inglês,1.0,160.0,180.0,160.0,200.0,180.0,880.0,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12705,481737,Campinas,35,F,1,branca,1,Andradas,MG,1,...,66.7,Inglês,1.0,120.0,120.0,120.0,140.0,140.0,640.0,Sim
12805,485567,Campinas,23,M,1,parda,1,Campinas,SP,1,...,374.2,Espanhol,1.0,120.0,120.0,120.0,120.0,40.0,520.0,Sim
12905,488881,Campinas,23,M,1,branca,1,Caetité,BA,1,...,668.9,Inglês,1.0,120.0,120.0,140.0,140.0,160.0,680.0,Sim
13005,492539,Campinas,27,M,1,preta,1,Campinas,SP,1,...,488.4,Espanhol,1.0,120.0,120.0,100.0,120.0,80.0,540.0,Não
13105,496216,Campinas,17,F,1,parda,1,Campinas,SP,2,...,426.3,Espanhol,1.0,120.0,180.0,120.0,120.0,60.0,600.0,Sim

## **FORMA ALTERNATIVA**

In [ ]:
# fixa a seleção aleatória
np.random.seed(30)
# declaramos as seguintes variáveis aleatórias
inicio = np.random.choice(10, 1)
passo = np.random.randint(100, 150, 1)

In [ ]:
inicio

array([5])

In [ ]:
passo

array([137])

In [ ]:
# cria o conjunto de índices para seleção posterior 
indices2 = np.arange(inicio, len(enem_campinas), passo)
indices2

array([    5,   142,   279,   416,   553,   690,   827,   964,  1101,
        1238,  1375,  1512,  1649,  1786,  1923,  2060,  2197,  2334,
        2471,  2608,  2745,  2882,  3019,  3156,  3293,  3430,  3567,
        3704,  3841,  3978,  4115,  4252,  4389,  4526,  4663,  4800,
        4937,  5074,  5211,  5348,  5485,  5622,  5759,  5896,  6033,
        6170,  6307,  6444,  6581,  6718,  6855,  6992,  7129,  7266,
        7403,  7540,  7677,  7814,  7951,  8088,  8225,  8362,  8499,
        8636,  8773,  8910,  9047,  9184,  9321,  9458,  9595,  9732,
        9869, 10006, 10143, 10280, 10417, 10554, 10691, 10828, 10965,
       11102, 11239, 11376, 11513, 11650, 11787, 11924, 12061, 12198,
       12335, 12472, 12609, 12746, 12883, 13020, 13157])

In [ ]:
# visualiza o tamanho
indices2.size

97

In [ ]:
# selecionamos os dados usando os indices
amostra2_camp = enem_campinas.iloc[indices2,:]
amostra2_camp

,index,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
5,186,Campinas,19,F,1,branca,1,Campinas,SP,1,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
142,6519,Campinas,26,M,0,preta,1,Montalvânia,MG,1,...,364.9,Inglês,1.0,120.0,200.0,140.0,120.0,200.0,780.0,Não
279,12280,Campinas,20,F,1,branca,1,Campinas,SP,1,...,46.7,Inglês,1.0,120.0,120.0,80.0,100.0,20.0,440.0,Sim
416,18436,Campinas,22,F,2,preta,1,Iaçu,BA,1,...,586.7,Espanhol,1.0,100.0,120.0,120.0,100.0,80.0,520.0,Sim
553,23717,Campinas,18,M,1,parda,1,Batalha,AL,1,...,48.4,Inglês,1.0,80.0,80.0,80.0,80.0,0.0,320.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12609,478519,Campinas,23,F,1,branca,1,Campinas,SP,1,...,592.2,Inglês,1.0,140.0,120.0,120.0,120.0,180.0,680.0,Sim
12746,483431,Campinas,18,F,1,branca,1,Campinas,SP,1,...,55.2,Inglês,1.0,140.0,120.0,120.0,140.0,100.0,620.0,Sim
12883,488340,Campinas,19,F,1,branca,1,Campinas,SP,1,...,542.3,Espanhol,1.0,120.0,120.0,140.0,120.0,80.0,580.0,Sim
13020,493180,Campinas,33,F,0,branca,1,Guanambi,BA,1,...,396.7,Inglês,1.0,80.0,40.0,40.0,80.0,0.0,240.0,Sim
13157,498126,Campinas,17,M,1,branca,1,Campinas,SP,2,...,653.7,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim