## **AMOSTRAGEM ESTRATIFICADA**

In [1]:
# Importa as dependencias
import numpy as np
import pandas as pd

In [2]:
# Monta o drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# carrega os dados
enem_sp = pd.read_csv('/content/drive/MyDrive/UDEMY - Estatística para Análise de Dados/Moreno Marcos/microdados_enem_2019_sp_tratado.csv',
                      sep=',', encoding='iso-8859-1')
enem_sp.head()

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Santa Isabel,22,M,1,parda,1,Santa Izabel do Pará,PA,1,4,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,São Paulo,17,F,1,parda,1,Belém,PA,2,0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,São Bernardo do Campo,19,M,1,parda,1,São Bernardo do Campo,SP,2,0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,Embu-Guaçu,17,F,1,parda,1,Itacoatiara,AM,2,0,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,Guarulhos,23,F,1,branca,1,São Paulo,SP,1,5,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

Utilizaremos apenas os dados associados a CAMPINAS

In [7]:
# filtra os dados
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']
# reseta os índices para ordenação numérica
enem_campinas.reset_index(inplace=True, drop=True)
enem_campinas

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Campinas,17,F,1,branca,1,Juazeiro do Norte,CE,1,1,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
1,Campinas,19,F,1,parda,1,Juiz de Fora,MG,1,0,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
2,Campinas,17,F,1,branca,1,Lavras,MG,2,0,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
3,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
4,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13193,Campinas,18,M,1,branca,1,Campinas,SP,1,1,...,490.9,Inglês,1.0,120.0,100.0,100.0,100.0,0.0,420.0,Sim
13194,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
13195,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim
13196,Campinas,19,F,1,branca,1,Campinas,SP,1,2,...,416.9,Espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13197,Campinas,20,F,1,branca,1,Campinas,SP,1,3,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

Vamos considerar o atributo RACA para gerar os grupos que iremos separar.

In [8]:
enem_campinas['RACA'].value_counts()

branca           7507
parda            3652
preta            1510
amarela           279
nao_declarado     205
indigena           45
Name: RACA, dtype: int64

Primeiro filtramos por um valor da raça (Ex. branca) e logo selecionamos aleatoriamente uma amostra (Ex. 10%)

**Para quantidade pequena de grupos**

In [40]:
# define tipos de raca
racas = enem_campinas['RACA'].value_counts().index
# define fração de seleção
frac = .10
# define lista de grupos
grupos = []
# itera cada tipo de raca para seleção
for raca in racas:
    grupos.append(enem_campinas.loc[enem_campinas.RACA == raca].sample(frac=frac))
# concatenamos cada grupo numa única tabela
amos_estra = pd.concat(grupos)
amos_estra.reset_index(drop=True, inplace=True)
amos_estra

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Campinas,18,F,1,branca,1,Campinas,SP,2,0,...,763.1,Inglês,1.0,160.0,180.0,180.0,200.0,160.0,880.0,Sim
1,Campinas,23,F,1,branca,1,São Paulo,SP,1,6,...,738.4,Inglês,1.0,160.0,160.0,120.0,120.0,80.0,640.0,Sim
2,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,621.6,Inglês,1.0,180.0,120.0,180.0,160.0,160.0,800.0,Sim
3,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,812.9,Inglês,1.0,160.0,200.0,160.0,160.0,160.0,840.0,Sim
4,Campinas,17,F,1,branca,1,Caraguatatuba,SP,2,0,...,500.6,Inglês,1.0,120.0,120.0,100.0,120.0,100.0,560.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,Campinas,49,M,2,nao_declarado,1,Campinas,SP,1,13,...,469.5,Espanhol,1.0,120.0,120.0,120.0,100.0,100.0,560.0,Sim
1315,Campinas,26,F,1,indigena,1,Campinas,SP,1,8,...,583.8,Inglês,1.0,120.0,120.0,80.0,100.0,100.0,520.0,Não
1316,Campinas,20,F,1,indigena,1,Campinas,SP,2,0,...,461.9,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim
1317,Campinas,17,F,1,indigena,3,NaN,NaN,2,0,...,434.9,Inglês,1.0,120.0,120.0,100.0,120.0,160.0,620.0,Sim
1318,Campinas,22,M,1,indigena,1,Campinas,SP,2,0,...,439.9,Espanhol,1.0,100.0,40.0,40.0,100.0,0.0,280.0,Não

Seleção estratificada final

In [70]:
amos_estra['RACA'].value_counts()

branca           751
parda            365
preta            151
amarela           28
nao_declarado     20
indigena           4
Name: RACA, dtype: int64

**Grandes quantidades de grupos**

In [87]:
enem_campinas['NO_MUNICIPIO_NASCIMENTO'].value_counts().index.size

924

In [73]:
# define nomes dos grupos
nomes = enem_campinas['NO_MUNICIPIO_NASCIMENTO'].value_counts().index
# define fração de seleção
frac = .10
# declara variável para armazenar seleção
grupos = []
# itera cada grupo para seleção
for nome in nomes:
    grupos.append(enem_campinas.loc[enem_campinas.NO_MUNICIPIO_NASCIMENTO == nome].sample(frac=frac))
# concatenamos a amaostra de cada grupo numa única tabela
amos_estra = pd.concat(grupos)
amos_estra.reset_index(drop=True, inplace=True)
amos_estra['NO_MUNICIPIO_NASCIMENTO'].value_counts()

Campinas          977
São Paulo          37
Valinhos            5
Rio de Janeiro      5
Sumaré              5
                 ...
Itapeva             1
Espinosa            1
Jequié              1
São Carlos          1
Mococa              1
Name: NO_MUNICIPIO_NASCIMENTO, Length: 108, dtype: int64

## **AMOSTRAGEM POR CONGLOMERADO (AGRUPAMENTO)**

In [ ]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']

In [ ]:
escolas_publicas.shape

(4175, 28)

In [ ]:
escolas_publicas

       NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
51         1,90E+11                Campinas  ...         740.0      Sim
116        1,90E+11                Campinas  ...         340.0      Sim
325        1,90E+11                Campinas  ...         480.0      Sim
949        1,90E+11                Campinas  ...         660.0      Sim
1004       1,90E+11                Campinas  ...         420.0      Não
...             ...                     ...  ...           ...      ...
499530     1,90E+11                Campinas  ...         660.0      Sim
499640     1,90E+11                Campinas  ...         280.0      Sim
499691     1,90E+11                Campinas  ...         600.0      Sim
499749     1,90E+11                Campinas  ...         440.0      Sim
499862     1,90E+11                Campinas  ...         640.0      Sim

[4175 rows x 28 columns]

In [ ]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts()
amostras

35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ...
35126846.0      1
35112252.0      1
26078562.0      1
35039834.0      1
35016559.0      1
Name: CO_ESCOLA, Length: 186, dtype: int64

In [ ]:
amostras.index

Float64Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0,
              35047200.0, 35901097.0, 35045949.0, 35018235.0, 35018302.0,
              ...
              35045962.0, 35112773.0, 35924672.0, 35042523.0, 35018181.0,
              35126846.0, 35112252.0, 26078562.0, 35039834.0, 35016559.0],
             dtype='float64', length=186)

In [ ]:
amostragem = np.random.choice(a=[0,1],size=186, replace=True, p=[0.85, 0.15])

In [ ]:
amostragem

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [ ]:
amos_conglomerado = amostras.loc[amostragem == 1]

In [ ]:
amos_conglomerado

35018797.0    124
35901097.0     87
35045949.0     84
35018302.0     73
35045664.0     60
35018570.0     49
35045950.0     34
35018120.0     32
35924945.0     29
35467765.0     23
35913984.0     22
35039895.0     20
35907376.0     19
35018910.0     13
35901124.0     12
35430705.0      8
35907397.0      7
35018867.0      6
35466682.0      5
35004766.0      4
35018119.0      4
35165062.0      4
35179905.0      3
35144757.0      3
35112513.0      3
35011343.0      3
35045524.0      2
35112896.0      2
35985296.0      2
35045724.0      1
26127741.0      1
35445757.0      1
35018181.0      1
35126846.0      1
35016559.0      1
Name: CO_ESCOLA, dtype: int64

In [ ]:
amos_conglomerado.shape

(35,)

In [ ]:
amos_conglomerado.index

Float64Index([35018797.0, 35901097.0, 35045949.0, 35018302.0, 35045664.0,
              35018570.0, 35045950.0, 35018120.0, 35924945.0, 35467765.0,
              35913984.0, 35039895.0, 35907376.0, 35018910.0, 35901124.0,
              35430705.0, 35907397.0, 35018867.0, 35466682.0, 35004766.0,
              35018119.0, 35165062.0, 35179905.0, 35144757.0, 35112513.0,
              35011343.0, 35045524.0, 35112896.0, 35985296.0, 35045724.0,
              26127741.0, 35445757.0, 35018181.0, 35126846.0, 35016559.0],
             dtype='float64')

In [ ]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([35112859.0, 35905471.0, 35045950.0, 35018508.0, 35905461.0,
              35914897.0, 35125568.0, 35127012.0, 35037965.0, 35018910.0,
              35127784.0, 35925962.0, 35907397.0, 35118084.0, 35579403.0,
              35458569.0, 35985296.0, 35045724.0, 35150095.0, 35138769.0,
              35337833.0, 35500012.0, 26127741.0, 35462342.0, 35445757.0,
              35058836.0, 35035956.0])]

In [ ]:
amos_conglomerado

       NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
2066       1,90E+11                Campinas  ...         940.0      Sim
5050       1,90E+11                Campinas  ...         720.0      Sim
5267       1,90E+11                Campinas  ...         560.0      Sim
6279       1,90E+11                Campinas  ...         460.0      Sim
6389       1,90E+11                Campinas  ...         580.0      Sim
...             ...                     ...  ...           ...      ...
481186     1,90E+11                Campinas  ...         540.0      Sim
487155     1,90E+11                Campinas  ...         480.0      Sim
491722     1,90E+11                Campinas  ...         300.0      Sim
493548     1,90E+11                Campinas  ...         700.0      Sim
499026     1,90E+11                Campinas  ...         320.0      Sim

[293 rows x 28 columns]