## **AMOSTRAGEM POR CONGLOMERADO**

In [86]:
# Importa as dependencias
import numpy as np
import pandas as pd
from math import isnan

In [2]:
# Monta o drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# carrega os dados
enem_sp = pd.read_csv('/content/drive/MyDrive/UDEMY - Estatística para Análise de Dados/Moreno Marcos/microdados_enem_2019_sp_tratado.csv',
                      sep=',', encoding='iso-8859-1')
enem_sp.head()

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Santa Isabel,22,M,1,parda,1,Santa Izabel do Pará,PA,1,4,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,São Paulo,17,F,1,parda,1,Belém,PA,2,0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,São Bernardo do Campo,19,M,1,parda,1,São Bernardo do Campo,SP,2,0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,Embu-Guaçu,17,F,1,parda,1,Itacoatiara,AM,2,0,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,Guarulhos,23,F,1,branca,1,São Paulo,SP,1,5,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

Utilizaremos apenas os dados associados a CAMPINAS

In [4]:
# filtra os dados
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']
# reseta os índices para ordenação numérica
enem_campinas.reset_index(inplace=True, drop=True)
enem_campinas

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Campinas,17,F,1,branca,1,Juazeiro do Norte,CE,1,1,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
1,Campinas,19,F,1,parda,1,Juiz de Fora,MG,1,0,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
2,Campinas,17,F,1,branca,1,Lavras,MG,2,0,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
3,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
4,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13193,Campinas,18,M,1,branca,1,Campinas,SP,1,1,...,490.9,Inglês,1.0,120.0,100.0,100.0,100.0,0.0,420.0,Sim
13194,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
13195,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim
13196,Campinas,19,F,1,branca,1,Campinas,SP,1,2,...,416.9,Espanhol,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13197,Campinas,20,F,1,branca,1,Campinas,SP,1,3,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

Agora iremos a considerar apenas escolas públicas em Campinas.

In [25]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']
escolas_publicas.reset_index(drop=True, inplace=True)
escolas_publicas.shape

(4175, 35)

In [26]:
escolas_publicas

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Campinas,17,F,1,branca,1,Lavras,MG,2,0,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
1,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
2,Campinas,17,M,1,parda,1,Recife,PE,2,0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
3,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
4,Campinas,24,F,1,branca,1,Campinas,SP,2,0,...,359.8,Espanhol,1.0,120.0,40.0,100.0,100.0,60.0,420.0,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,491.6,Inglês,1.0,140.0,120.0,120.0,160.0,120.0,660.0,Sim
4171,Campinas,22,M,1,preta,1,Campinas,SP,2,0,...,365.4,Espanhol,1.0,80.0,60.0,60.0,80.0,0.0,280.0,Sim
4172,Campinas,17,F,1,preta,1,Campinas,SP,2,0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
4173,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
4174,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim

Observe que a coluna CO_ESCOLA póssui valores faltantes.

In [29]:
escolas_publicas['CO_ESCOLA'].isnull().sum()

766

No entanto, isso não é problema porque o método value_counts() desconsidera valores faltantes na sua contagem.

In [32]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts()
amostras.isnull().sum()

0

Criamos uma variável que vai armazenar os códigos das escolas públicas como sendo os grupos. Perceba a quantidade de alunos por grupo.

In [125]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts()
amostras

35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ...
35462822.0      1
35058836.0      1
35112926.0      1
35017255.0      1
35047053.0      1
Name: CO_ESCOLA, Length: 186, dtype: int64

Podemos acessar aos código das escolas da seguinte forma. Repare o número de escolas públicas.

In [128]:
amostras.index

Float64Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0,
              35047200.0, 35901097.0, 35045949.0, 35018235.0, 35018302.0,
              ...
              35018181.0, 35445757.0, 35045724.0, 35432842.0, 35039834.0,
              35462822.0, 35058836.0, 35112926.0, 35017255.0, 35047053.0],
             dtype='float64', length=186)

Agora vamos a criar uma variável que armazene a seleção aleatória (amostragem). Repare que o tamanho deve ser igual ao tamanho da quantidade de escolas (como mostrada acima). Além disso, o critério de selção de grupos é 15% (do total de grupos) -  representado com o número "1".

In [137]:
np.random.seed(1)
amostragem = np.random.choice(a=[0,1], size=amostras.index.size, replace=True, p=[0.85, 0.15])
amostragem

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Agora usando a amostragem anterior, iremos a selecionar os grupos (variável amostras) e armazenar numa variável para uso posterior.

In [161]:
amos_conglomerado = amostras.loc[amostragem == 1]
amos_conglomerado

35018314.0    58
35018284.0    43
35018259.0    36
35018521.0    36
35045950.0    34
35018491.0    31
35445897.0    27
35467765.0    23
35040873.0    15
35923394.0    14
35018417.0    13
35907406.0    12
35901088.0     9
35042626.0     9
35112884.0     9
35018399.0     8
35437153.0     7
35004252.0     6
35018107.0     6
35131982.0     6
35040859.0     5
35018119.0     4
35915592.0     3
35179905.0     3
35045524.0     2
35914009.0     1
35112689.0     1
35441648.0     1
Name: CO_ESCOLA, dtype: int64

In [162]:
amos_conglomerado.shape

(28,)

In [163]:
amos_conglomerado.index

Float64Index([35018314.0, 35018284.0, 35018259.0, 35018521.0, 35045950.0,
              35018491.0, 35445897.0, 35467765.0, 35040873.0, 35923394.0,
              35018417.0, 35907406.0, 35901088.0, 35042626.0, 35112884.0,
              35018399.0, 35437153.0, 35004252.0, 35018107.0, 35131982.0,
              35040859.0, 35018119.0, 35915592.0, 35179905.0, 35045524.0,
              35914009.0, 35112689.0, 35441648.0],
             dtype='float64')

Finalmente iremos pegar os valores da tabela que considera escola públicas em Campinhas usando o indices anteriores (variável amos_conglomerado).

In [164]:
colegios = amos_conglomerado.index
amos_conglomerado_final = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin(colegios)]
amos_conglomerado_final.reset_index(drop=True, inplace=True)
amos_conglomerado_final

,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,NO_MUNICIPIO_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,Campinas,17,F,1,parda,1,Campinas,SP,2,0,...,42.3,Inglês,1.0,140.0,120.0,120.0,140.0,80.0,600.0,Sim
1,Campinas,18,M,1,preta,1,Campinas,SP,2,0,...,638.9,Inglês,1.0,120.0,140.0,140.0,140.0,100.0,640.0,Sim
2,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,728.7,Inglês,1.0,140.0,160.0,140.0,140.0,140.0,720.0,Sim
3,Campinas,17,F,1,preta,1,Campinas,SP,2,0,...,475.6,Inglês,1.0,160.0,120.0,160.0,180.0,100.0,720.0,Sim
4,Campinas,17,F,1,parda,1,Jaguaquara,BA,2,0,...,652.3,Espanhol,1.0,120.0,160.0,120.0,140.0,180.0,720.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,Campinas,17,M,1,branca,1,Campinas,SP,2,0,...,392.1,Inglês,1.0,100.0,40.0,40.0,120.0,0.0,300.0,Sim
418,Campinas,17,M,1,parda,1,Campinas,SP,2,0,...,668.5,Inglês,1.0,160.0,120.0,120.0,120.0,40.0,560.0,Sim
419,Campinas,17,M,1,parda,1,Hortolândia,SP,2,0,...,51.0,Inglês,1.0,100.0,200.0,120.0,140.0,0.0,560.0,Sim
420,Campinas,17,F,1,branca,1,Campinas,SP,2,0,...,546.4,Inglês,1.0,100.0,120.0,100.0,120.0,40.0,480.0,Sim
421,Campinas,18,F,1,parda,1,Campinas,SP,2,0,...,487.5,Espanhol,1.0,120.0,120.0,120.0,100.0,60.0,520.0,Não